create extension if not exists citext;

create table users (
  id bigint primary key generated by default as identity,
  email citext not null unique,
  password_hash varchar(255),
  created_at timestamp(0) not null default (now() at time zone 'Asia/Bangkok'),
  updated_at timestamp(0) not null default (now() at time zone 'Asia/Bangkok')
);